//Main category
export const CREATE_MAINCATEGORY="CREATE_MAINCATEGORY";
export const CREATE_MAINCATEGORY_REDUCER="CREATE_MAINCATEGORY_REDUCER";
export const UPDATE_MAINCATEGORY="UPDATE_MAINCATEGORY";
export const UPDATE_MAINCATEGORY_REDUCER="UPDATE_MAINCATEGORY_REDUCER";
export const GET_MAINCATEGORY="GET_MAINCATEGORY";
export const GET_MAINCATEGORY_REDUCER="GET_MAINCATEGORY_REDUCER";
export const DELETE_MAINCATEGORY="DELETE_MAINCATEGORY";
export const DELETE_MAINCATEGORY_REDUCER="DELETE_MAINCATEGORY_REDUCER";
//Sub category
export const CREATE_SUBCATEGORY="CREATE_SUBCATEGORY";
export const CREATE_SUBCATEGORY_REDUCER="CREATE_SUBCATEGORY_REDUCER";
export const UPDATE_SUBCATEGORY="UPDATE_SUBCATEGORY";
export const UPDATE_SUBCATEGORY_REDUCER="UPDATE_SUBCATEGORY_REDUCER";
export const GET_SUBCATEGORY="GET_SUBCATEGORY";
export const GET_SUBCATEGORY_REDUCER="GET_SUBCATEGORY_REDUCER";
export const DELETE_SUBCATEGORY="DELETE_SUBCATEGORY";
export const DELETE_SUBCATEGORY_REDUCER="DELETE_SUBCATEGORY_REDUCER";
//Brand
export const CREATE_BRAND="CREATE_BRAND";
export const CREATE_BRAND_REDUCER="CREATE_BRAND_REDUCER";
export const UPDATE_BRAND="UPDATE_BRAND";
export const UPDATE_BRAND_REDUCER="UPDATE_BRAND_REDUCER";
export const GET_BRAND="GET_BRAND";
export const GET_BRAND_REDUCER="GET_BRAND_REDUCER";
export const DELETE_BRAND="DELETE_BRAND";
export const DELETE_BRAND_REDUCER="DELETE_BRAND_REDUCER";
//Product
export const CREATE_PRODUCT="CREATE_PRODUCT";
export const CREATE_PRODUCT_REDUCER="CREATE_PRODUCT_REDUCER";
export const UPDATE_PRODUCT="UPDATE_PRODUCT";
export const UPDATE_PRODUCT_REDUCER="UPDATE_PRODUCT_REDUCER";
export const GET_PRODUCT="GET_PRODUCT";
export const GET_PRODUCT_REDUCER="GET_PRODUCT_REDUCER";
export const DELETE_PRODUCT="DELETE_PRODUCT";
export const DELETE_PRODUCT_REDUCER="DELETE_PRODUCT_REDUCER";

//Setting
export const CREATE_SETTING="CREATE_SETTING";
export const CREATE_SETTING_REDUCER="CREATE_SETTING_REDUCER";
export const UPDATE_SETTING="UPDATE_SETTING";
export const UPDATE_SETTING_REDUCER="UPDATE_SETTING_REDUCER";
export const GET_SETTING="GET_SETTING";
export const GET_SETTING_REDUCER="GET_SETTING_REDUCER";
export const DELETE_SETTING="DELETE_SETTING";
export const DELETE_SETTING_REDUCER="DELETE_SETTING_REDUCER";
//Feature
export const CREATE_FEATURE="CREATE_FEATURE";
export const CREATE_FEATURE_REDUCER="CREATE_FEATURE_REDUCER";
export const UPDATE_FEATURE="UPDATE_FEATURE";
export const UPDATE_FEATURE_REDUCER="UPDATE_FEATURE_REDUCER";
export const GET_FEATURE="GET_FEATURE";
export const GET_FEATURE_REDUCER="GET_FEATURE_REDUCER";
export const DELETE_FEATURE="DELETE_FEATURE";
export const DELETE_FEATURE_REDUCER="DELETE_FEATURE_REDUCER";
//FAQ
export const CREATE_FAQ="CREATE_FAQ";
export const CREATE_FAQ_REDUCER="CREATE_FAQ_REDUCER";
export const UPDATE_FAQ="UPDATE_FAQ";
export const UPDATE_FAQ_REDUCER="UPDATE_FAQ_REDUCER";
export const GET_FAQ="GET_FAQ";
export const GET_FAQ_REDUCER="GET_FAQ_REDUCER";
export const DELETE_FAQ="DELETE_FAQ";
export const DELETE_FAQ_REDUCER="DELETE_FAQ_REDUCER";
//Cart
export const CREATE_CART="CREATE_CART";
export const CREATE_CART_REDUCER="CREATE_CART_REDUCER";
export const UPDATE_CART="UPDATE_CART";
export const UPDATE_CART_REDUCER="UPDATE_CART_REDUCER";
export const GET_CART="GET_CART";
export const GET_CART_REDUCER="GET_CART_REDUCER";
export const DELETE_CART="DELETE_CART";
export const DELETE_CART_REDUCER="DELETE_CART_REDUCER";
//WishList
export const CREATE_WISHLIST="CREATE_WISHLIST";
export const CREATE_WISHLIST_REDUCER="CREATE_WISHLIST_REDUCER";
export const GET_WISHLIST="GET_WISHLIST";
export const GET_WISHLIST_REDUCER="GET_WISHLIST_REDUCER";
export const DELETE_WISHLIST="DELETE_WISHLIST";
export const DELETE_WISHLIST_REDUCER="DELETE_WISHLIST_REDUCER";
//Checkout 
export const CREATE_CHECKOUT="CREATE_CHECKOUT";
export const CREATE_CHECKOUT_REDUCER="CREATE_CHECKOUT_REDUCER";
export const GET_CHECKOUT="GET_CHECKOUT";
export const GET_CHECKOUT_REDUCER="GET_CHECKOUT_REDUCER";
export const DELETE_CHECKOUT="DELETE_CHECKOUT";
export const DELETE_CHECKOUT_REDUCER="DELETE_CHECKOUT_REDUCER";
export const UPDATE_CHECKOUT="UPDATE_CHECKOUT";
export const UPDATE_CHECKOUT_REDUCER="UPDATE_CHECKOUT_REDUCER";
//Testimonial
export const CREATE_TESTIMONIAL="CREATE_TESTIMONIAL";
export const CREATE_TESTIMONIAL_REDUCER="CREATE_TESTIMONIAL_REDUCER";
export const GET_TESTIMONIAL="GET_TESTIMONIAL";
export const GET_TESTIMONIAL_REDUCER="GET_TESTIMONIAL_REDUCER";
export const UPDATE_TESTIMONIAL="UPDATE_TESTIMONIAL";
export const UPDATE_TESTIMONIAL_REDUCER="UPDATE_TESTIMONIAL_REDUCER";
//NeewsLetter
export const CREATE_NEWSLETTER="CREATE_NEWSLETTER";
export const CREATE_NEWSLETTER_REDUCER="CREATE_NEWSLETTER_REDUCER";
export const GET_NEWSLETTER="GET_NEWSLETTER";
export const GET_NEWSLETTER_REDUCER="GET_NEWSLETTER_REDUCER";
//Contact Us
export const CREATE_CONTACT="CREATE_CONTACT";
export const CREATE_CONTACT_REDUCER="CREATE_CONTACT_REDUCER";
export const GET_CONTACT="GET_CONTACT";
export const GET_CONTACT_REDUCER="GET_CONTACT_REDUCER";
export const DELETE_CONTACT="DELETE_CONTACT";
export const DELETE_CONTACT_REDUCER="DELETE_CONTACT_REDUCER";
export const UPDATE_CONTACT="UPDATE_CONTACT";
export const UPDATE_CONTACT_REDUCER="UPDATE_CONTACT_REDUCER";